name: Run a Python script

on: [workflow_dispatch]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Run script
      run: |
        python -m pip install -U pip
        pip install tensorflow
        python ./simple.py

    - name: Commit result
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add .
        git commit -m "Train models"
        git push
        
