name: Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Echo something
      run: echo "Hello World"

    - name: Update test.txt
      run: echo ${{ github.sha }} > test.txt
