name: Test

on:
  push:
    paths:
      - test.txt

  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Echo something
      run: echo "Hello World"

    - name: Update test.txt
      run: echo ${{ github.sha }} > test.txt

    - name: Commit changes
      run: |
        git config --global user.email "hsxb2024@163.com"
        git config --global user.name "haxiaobai"
        git add .
        git commit -m "Update test.txt"
        git push
